---
title: "Terms of Service"
author: "Connor Krenzer"
date: "7/15/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

# Introduction

Add writing here.

```{r setup-packages, include = FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      include = FALSE,
                      results = "show",
                      error = FALSE,
                      warning = FALSE,
                      message = FALSE)


# PACKAGES
if(!require(pacman)) install.packages("pacman")

# Data Import Packages
pacman::p_load(readtext)

# General Packages
pacman::p_load(stringr, dplyr, ggplot2)

# Text Mining Packages
pacman::p_load(tidytext, textdata)

# Setting ggplot to the dark theme
ggplot2::theme_set(theme_dark())
# The colors that represent each company
company_colors <- c(Amazon = "#FF9900",
                    DuckDuckGo = "#ec2127",
                    Facebook = "#4267B2",
                    GitHub = "#000000",
                    LinkedIn = "#007bb6",
                    Spotify = "#1DB954",
                    YouTube = "#FF0000")



# DATA IMPORT
tos <- readtext(file = "data/") %>% 
  rename(company = doc_id) %>% 
  mutate(company = str_remove_all(company, "_Terms_of_Service.txt"),
         text = str_to_lower(text))


```



```{r number of characters}

tos %>% 
  mutate(number_of_characters_in_TOS = str_length(text)) %>% 
  arrange(desc(number_of_characters_in_TOS)) %>% 
  ggplot() +
  geom_col(mapping = aes(x = reorder(company,
                                     number_of_characters_in_TOS),
                         y = number_of_characters_in_TOS,
                         fill = company),
           show.legend = FALSE) +
  ggtitle("Number of Characters Used in Terms of Service") +
  xlab("Company") +
  ylab("Number of Characters") +
  scale_fill_manual(values = company_colors) +
  coord_flip()

```





```{r unigrams}

unigrams <- tos %>% 
  unnest_tokens(word, text)

ungrouped_unigram_counts <- count(unigrams, word, sort = FALSE)
unigram_counts <- count(unigrams, company, word, sort = FALSE)

```




```{r my Porter stemmer}

# Remember as you read this that replacement operations inside the mutate calls refer to entire vectors of words while the operations inside a case_when() call refers to individual words
my_porter_stemmer <- function(unigram_df){
  # The implementation of the Porter stemmer algorithm as I understand it,
  # described in Julia Silge's book:
  # https://smltar.com/stemming.html#understand-a-stemming-algorithm
  # or more formally from:
  # https://vijinimallawaarachchi.com/2017/05/09/porter-stemming-algorithm/
  
  
  # Step 1a
  unigram_df <- unigram_df %>% 
    mutate(m = str_count(word, pattern = "[aeiou]+[^aeiou]+"),
           word = str_replace_all(word, "sses$", "ss") %>% 
             str_replace_all("ies$", "i") %>% 
             str_replace("([a-rt-z])(?<!s)s$", "\\1")) #remove final single 's' letters
  
  # Step 1b
  unigram_df <- unigram_df %>% 
    mutate(word = m > 0 && str_detect(word, "eed$") ~ str_replace(word, "eed$", "ee"),
           word = case_when(
             str_detect(word, "ed$") && str_detect(str_sub(word, end = -3), "[aeiou]") ~ step_1b(word = word, suffix = "ed$", m = m),
             str_detect(word, "ing$") && str_detect(str_sub(word, end = -4), "[aeiou]") ~ step_1b(word = word, suffix = "ing$", m = m),
             
             TRUE ~ word
           ))
  
  
  # Step 1c
  unigram_df <- unigram_df %>% 
    mutate(word = if_else(condition = str_detect(word, "y$") && str_detect(str_sub(word, end = -1), "aeiou"),
                          true = str_replace(string = word, pattern = "y$", replacement = "i"),
                          false = word))
  
  # Step 2
  unigram_df <- unigram_df %>% 
    mutate(word = case_when(
      m > 0 && str_detect(word, "ational$") ~ str_replace(string = word, pattern = "ational$", replacement = "ate"),
      m > 0 && str_detect(word, "tional$") ~ str_replace(string = word, pattern = "tional$", replacement = "tion"),
      m > 0 && str_detect(word, "enci$") ~ str_replace(string = word, pattern = "enci$", replacement = "ence"),
      m > 0 && str_detect(word, "anci$") ~ str_replace(string = word, pattern = "anci$", replacement = "ance"),
      m > 0 && str_detect(word, "izer$") ~ str_replace(string = word, pattern = "izer$", replacement = "ize"),
      m > 0 && str_detect(word, "abli$") ~ str_replace(string = word, pattern = "abli$", replacement = "able"),
      m > 0 && str_detect(word, "alli$") ~ str_replace(string = word, pattern = "alli$", replacement = "al"),
      m > 0 && str_detect(word, "entli$") ~ str_replace(string = word, pattern = "entli$", replacement = "ent"),
      m > 0 && str_detect(word, "eli$") ~ str_replace(string = word, pattern = "eli$", replacement = "e"),
      m > 0 && str_detect(word, "ousli$") ~ str_replace(string = word, pattern = "ousli$", replacement = "ous"),
      m > 0 && str_detect(word, "ization$") ~ str_replace(string = word, pattern = "ization$", replacement = "ize"),
      m > 0 && str_detect(word, "ation$") ~ str_replace(string = word, pattern = "ation$", replacement = "ate"),
      m > 0 && str_detect(word, "ator$") ~ str_replace(string = word, pattern = "ator$", replacement = "ate"),
      m > 0 && str_detect(word, "alism$") ~ str_replace(string = word, pattern = "alism$", replacement = "al"),
      m > 0 && str_detect(word, "iveness$") ~ str_replace(string = word, pattern = "iveness$", replacement = "ive"),
      m > 0 && str_detect(word, "fulness$") ~ str_replace(string = word, pattern = "fulness$", replacement = "ful"),
      m > 0 && str_detect(word, "ousness$") ~ str_replace(string = word, pattern = "ousness$", replacement = "ous"),
      m > 0 && str_detect(word, "aliti$") ~ str_replace(string = word, pattern = "aliti$", replacement = "al"),
      m > 0 && str_detect(word, "iviti$") ~ str_replace(string = word, pattern = "iviti$", replacement = "ive"),
      m > 0 && str_detect(word, "biliti$") ~ str_replace(string = word, pattern = "biliti$", replacement = "ble"),
      
      TRUE ~ word
    ))
  
  
  
  # Step 3
  unigram_df <- unigram_df %>% 
    mutate(word = case_when(
      m > 0 && str_detect(word, "$") ~ str_replace(string = word, pattern = "$", replacement = ""),
      
      
      
      TRUE ~ word
      ))
  
}

# CALCULATING MEASURE
words <- c("tree", "trouble", "troubles", "collection", "management", "conclude", "revise", "oaten")
measure <- str_count(words, pattern = "[aeiou]+[^aeiou]+")






step_1b <- function(word, suffix, m){
  
  word %>% 
    str_remove(suffix) %>% 
    str_replace("at$", "ate") %>% # Begin the 'if the second or third of the rules in step 1b is successful...'
    str_replace("bl$", "ble") %>% 
    str_replace("iz$", "ize") %>% 
    str_replace("([bcdfghjklmnpqrvwxy]){2}$", "\\1") %>%  # *d and not (*L, *S, or *Z)) --> single letter
    if_else(condition = m == 1, # replace *o with 'e' if m is 1 and do nothing otherwise
            true = str_replace(string = ., pattern = "[^aeiou]{1}[aeiou]{1}[^aeiou]{1}$", replacement =  "e"),
            false =  .) %>% 
    return()
  
}#end of step_1b()




```




```{r common words}

ungrouped_unigram_counts %>%  
  filter(!word %in% stop_words$word,
         word != "â") %>% 
  slice_max(order_by = n, n = 25) %>% 
  ggplot() +
  geom_col(mapping = aes(x = reorder(word, n), y = n, fill = word),
           show.legend = FALSE) +
  ggtitle("Most Common Words Among All TOS Policies") +
  xlab("Word") +
  ylab("Number of Uses") +
  coord_flip()




ungrouped_unigram_counts %>%  
  filter(!word %in% stop_words$word) %>% 
  slice_max(order_by = n, n = 25) %>% as.data.frame

```


